=== lorin/activitygraph/trunk/data/activitygraph.dtd
<!ELEMENT ActivityGraph (SeriesGroup*)>
 <!ATTLIST ActivityGraph timezone CDATA #IMPLIED>
<!ELEMENT SeriesGroup (Series*)>
 <!ATTLIST SeriesGroup name CDATA #REQUIRED>
<!ELEMENT Series ((Interval|Point)*)>
  <!ATTLIST Series name CDATA #REQUIRED>
  <!ATTLIST Series color CDATA #IMPLIED>
<!ELEMENT Interval EMPTY>
  <!ATTLIST Interval start CDATA #REQUIRED>
  <!ATTLIST Interval end CDATA #REQUIRED>
  <!ATTLIST Interval text CDATA #IMPLIED>
  <!ATTLIST Interval note CDATA #IMPLIED>
<!ELEMENT Point EMPTY>
 <!ATTLIST Point time CDATA #REQUIRED>
 <!ATTLIST Point text CDATA #IMPLIED>
 <!ATTLIST Point note CDATA #IMPLIED>

=== lorin/activitygraph/data/demo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ActivityGraph SYSTEM "http://activitygraph.googlecode.com/svn/trunk/data/activitygraph.dtd">
<ActivityGraph>
  <SeriesGroup name="Activities">
    <Series name="thinking">
      <Interval end="1149189300" start="1149189060" note="truth-thinking-tooltip1" />
      <Interval end="1149191520" start="1149191220" />
      <Interval end="1149527700" start="1149527460" />
    </Series>
    <Series name="serial">
      <Interval end="1149190920" start="1149189300" note="truth-serial-tooltip1" />
      <Interval end="1149191220" start="1149190920" note="truth-serial-tooltip2" />
      <Interval end="1149193440" start="1149191520" note="truth-serial-tooltip3" />
    </Series>
    <Series name="parallel">
      <Interval end="1149530340" start="1149527700" note="truth-parallel-tooltip1" />
    </Series>
    <Series name="debugging">
      <Interval end="1149195300" start="1149193440" note="truth-degugging-tooltip1"/>
      <Interval end="1149260460" start="1149256980" />
      <Interval end="1149527460" start="1149526980" />
      <Interval end="1149531840" start="1149530340" />
      <Interval end="1149626220" start="1149621300" />
      <Interval end="1149962640" start="1149962520" />
      <Interval end="1150396320" start="1150394520" />
    </Series>
    <Series name="testing">
      <Interval end="1150398480" start="1150396320" />
    </Series>
  </SeriesGroup>
  <SeriesGroup name="Events">
    <Series name="viewing">
      <Point time="1149189170" note="Events-viewing-tooltip1" />
      <Point time="1149189204" note="Events-viewing-tooltip2" />
      <Point time="1149189214" />
      <Point time="1149189223" />
      <Point time="1149189236" />
      <Point time="1149189663" />
      <Point time="1149190372" />
      <Point time="1149191191" />
      <Point time="1149191194" />
      <Point time="1149191245" />
      <Point time="1149191249" />
      <Point time="1149191275" />
      <Point time="1149191284" />
      <Point time="1149191288" />
      <Point time="1149193483" />
      <Point time="1149193496" />
      <Point time="1149193502" />
      <Point time="1149193506" />
      <Point time="1149193667" />
      <Point time="1149193675" />
      <Point time="1149193680" />
      <Point time="1149193682" />
      <Point time="1149193689" />
      <Point time="1149193918" />
      <Point time="1149193921" />
      <Point time="1149193927" />
      <Point time="1149194766" />
      <Point time="1149195042" />
      <Point time="1149195114" />
      <Point time="1149257158" />
      <Point time="1149257170" />
      <Point time="1149257199" />
      <Point time="1149257209" />
      <Point time="1149257225" />
      <Point time="1149257230" />
      <Point time="1149257232" />
      <Point time="1149257234" />
      <Point time="1149257722" />
      <Point time="1149257736" />
      <Point time="1149257743" />
      <Point time="1149257823" />
      <Point time="1149257829" />
      <Point time="1149257833" />
      <Point time="1149257838" />
      <Point time="1149257887" />
      <Point time="1149257903" />
      <Point time="1149257976" />
      <Point time="1149257979" />
      <Point time="1149257981" />
      <Point time="1149257994" />
      <Point time="1149258038" />
      <Point time="1149258173" />
      <Point time="1149258182" />
      <Point time="1149258190" />
      <Point time="1149258194" />
      <Point time="1149258225" />
      <Point time="1149258230" />
      <Point time="1149258312" />
      <Point time="1149258316" />
      <Point time="1149260185" />
      <Point time="1149260193" />
      <Point time="1149260274" />
      <Point time="1149260278" />
      <Point time="1149260282" />
      <Point time="1149260287" />
      <Point time="1149260318" />
      <Point time="1149260322" />
      <Point time="1149527420" />
      <Point time="1149527436" />
      <Point time="1149527440" />
      <Point time="1149527446" />
      <Point time="1149527457" />
      <Point time="1149527459" />
      <Point time="1149530813" />
      <Point time="1149530837" />
      <Point time="1149530845" />
      <Point time="1149530882" />
      <Point time="1149530908" />
      <Point time="1149530911" />
      <Point time="1149530914" />
      <Point time="1149530926" />
      <Point time="1149530933" />
      <Point time="1149531050" />
      <Point time="1149531062" />
      <Point time="1149531092" />
      <Point time="1149531098" />
      <Point time="1149531205" />
      <Point time="1149531212" />
      <Point time="1149531218" />
      <Point time="1149531219" />
      <Point time="1149531220" />
      <Point time="1149531250" />
      <Point time="1149531266" />
      <Point time="1149531274" />
      <Point time="1149531278" />
      <Point time="1149531309" />
      <Point time="1149531378" />
      <Point time="1149621649" />
      <Point time="1149621653" />
      <Point time="1149621838" />
      <Point time="1149622148" />
      <Point time="1149622151" />
      <Point time="1149622153" />
      <Point time="1149622163" />
      <Point time="1149622167" />
      <Point time="1149622174" />
      <Point time="1149622340" />
      <Point time="1149622345" />
      <Point time="1149622349" />
      <Point time="1149622549" />
      <Point time="1149622552" />
      <Point time="1149622702" />
      <Point time="1149622817" />
      <Point time="1149622823" />
      <Point time="1149622903" />
      <Point time="1149623036" />
      <Point time="1149623181" />
      <Point time="1149623303" />
      <Point time="1149623605" />
      <Point time="1149623612" />
      <Point time="1149624773" />
      <Point time="1149624795" />
      <Point time="1149624802" />
      <Point time="1149624986" />
      <Point time="1149625095" />
      <Point time="1149625103" />
      <Point time="1149625138" />
      <Point time="1149625208" />
      <Point time="1149625215" />
      <Point time="1149625349" />
      <Point time="1149625543" />
      <Point time="1149963039" />
      <Point time="1149963042" />
      <Point time="1149964826" />
      <Point time="1149965168" />
      <Point time="1149965171" />
      <Point time="1149965182" />
      <Point time="1149965211" />
      <Point time="1149965226" />
      <Point time="1149965431" />
      <Point time="1149965439" />
      <Point time="1149965544" />
      <Point time="1149965601" />
      <Point time="1149965758" />
      <Point time="1149965776" />
      <Point time="1149965788" />
      <Point time="1149965793" />
      <Point time="1149965798" />
      <Point time="1149965800" />
      <Point time="1149965822" />
      <Point time="1149966182" />
      <Point time="1149966187" />
      <Point time="1149966762" />
      <Point time="1149966766" />
      <Point time="1149968705" />
      <Point time="1149969894" />
      <Point time="1149969897" />
      <Point time="1149969955" />
      <Point time="1149969958" />
      <Point time="1149970026" />
      <Point time="1149970033" />
      <Point time="1149970155" />
      <Point time="1149970158" />
      <Point time="1149970166" />
      <Point time="1149970174" />
      <Point time="1149970183" />
      <Point time="1149970205" />
      <Point time="1149970537" />
      <Point time="1149970542" />
      <Point time="1150394940" />
      <Point time="1150395164" />
      <Point time="1150395166" />
      <Point time="1150395192" />
      <Point time="1150395199" />
      <Point time="1150395201" />
      <Point time="1150395210" />
      <Point time="1150395216" />
      <Point time="1150395266" />
      <Point time="1150395274" />
      <Point time="1150395296" />
      <Point time="1150395299" />
      <Point time="1150395358" />
      <Point time="1150395361" />
      <Point time="1150395433" />
      <Point time="1150395436" />
      <Point time="1150395453" />
      <Point time="1150395474" />
      <Point time="1150396113" />
      <Point time="1150396121" />
      <Point time="1150396685" />
      <Point time="1150396693" />
      <Point time="1150396697" />
      <Point time="1150396731" />
      <Point time="1150396855" />
      <Point time="1150397107" />
      <Point time="1150397111" />
      <Point time="1150397292" />
      <Point time="1150397307" />
      <Point time="1150397719" />
      <Point time="1150397733" />
      <Point time="1150397788" />
      <Point time="1150397794" />
      <Point time="1150398364" />
      <Point time="1150398368" />
      <Point time="1150398381" />
      <Point time="1150398445" />
      <Point time="1150398454" />
    </Series>
    <Series name="filecommand">
      <Point time="1149189191" />
      <Point time="1149189217" />
      <Point time="1149189266" />
      <Point time="1149189268" />
      <Point time="1149189268" />
      <Point time="1149189660" />
      <Point time="1149190191" />
      <Point time="1149190377" />
      <Point time="1149191270" />
      <Point time="1149191289" />
      <Point time="1149191292" />
      <Point time="1149191293" />
      <Point time="1149191294" />
      <Point time="1149191297" />
      <Point time="1149191297" />
      <Point time="1149193471" />
      <Point time="1149193512" />
      <Point time="1149193923" />
      <Point time="1149194144" />
      <Point time="1149194144" />
      <Point time="1149194187" />
      <Point time="1149194190" />
      <Point time="1149194191" />
      <Point time="1149194236" />
      <Point time="1149194705" />
      <Point time="1149257015" />
      <Point time="1149257092" />
      <Point time="1149257120" />
      <Point time="1149257160" />
      <Point time="1149257185" />
      <Point time="1149257186" />
      <Point time="1149257201" />
